### ISSUE TITLE
TTW

### ISSUE THREAD

**Issue by Dweller131213** [peavers/peavers-ui#1]
Wanted to ask if  there will be full support for TTW and when we will get prepatch update tnx in advance

**Comment by peavers** [comment]
Hello! Yes should have an update in a day or so!

**Comment by peavers** [comment]
I've just pushed a build for TWW but it's a little rushed so might be buggy. Talent loading works which was my primary focus as a lot of the WoW APIs changed around that. Give it a go, and please raise any bugs you find here!
