### ISSUE TITLE
Addon not applying profiles

### ISSUE THREAD

**Issue by garlosh** [peavers/peavers-ui#3]
Hello, I'm having an issue where both profiles and weakauras simply don't work.

As an example, when I click in some button, it gives the message "Applying profile for: Details! Damage Meter" and doesn't do anything.

PS: I've already deleted all my addons and installed them again.

**Comment by peavers** [comment]
This should now be resolve, for the meantime I've had to remove a lot of the import profiles until I've got the time to just fix it all, but for now Bartender/Cell/Details should be working along with weakaura and talent imports.
