### ISSUE TITLE
Various errors on importing profiles to addons

### ISSUE THREAD

**Issue by Kharazidusk** [peavers/peavers-ui#4]
Fresh install, attempting to install profiles into the related addons.

**Plater error:** 
Message: Interface/AddOns/PeaversUI/src/Profiles/Plater.lua:9: attempt to call global 'IsAddOnLoaded' (a nil value)
Time: Mon Sep 30 20:09:41 2024
Count: 1
Stack: Interface/AddOns/PeaversUI/src/Profiles/Plater.lua:9: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@Interface/AddOns/PeaversUI/src/Profiles/Plater.lua"]:9: in function `apply'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:102: in function `ApplyProfile'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:49: in function <Interface/AddOns/PeaversUI/src/Options/Profiles.lua:48>

Locals: settings = "S33IYTnUsA)UO)ARynhBfE)soBov5l5INnXjvKNz2ZFMyBkjkB(hksTKuXXZuJFZ2AFK2xHF0na4vaskljNz2nN5KejkqGganaA04R)WfQxC(fJNhpDv6LEPxM5LCTF2LEHlVX7IjxmEvWLl9s8JYUCYQ5ZVmDP)0aVWld9)IF4fNPCXyVvjExojX37ZHbr(Ke4n1)IZu1UyC60KGLzxoZlZJueNHLZXXrPzjRMMfNCC8mFsbVkAAwqC09xTxQF489V)QvrbzNoJ9HxM4TWN8z)OVCU3Kq4J0Sf)2W7)X7VI9F5F6GdMh6LEZ9xnJizywN)tHXt9cV)QJF3zV80xD5lFZHJF9LN8tF4WZp9DND)vpVsEpAAC08GRhHz2jnYQYL3cVOvEHH3D)vtjTdz(3FL39xf5F79xL5)1SvjKhmpoH8TBGprfoVOGf1YYG5KgHO4SIA7OXli57lH34CAoneZLYYb7)K)kyfRTFgeT3hsK7KNDmk)NUW7AYZ3lVdy0uV0SJ8sgUoL7Zg7NDCCyCsEbTNkP7d)ZANrhgg((4GOS09k9Q(rZwJoKgn8xTkni6AE3cupVno5Z9S)4qE286vt4Dkx1Sw18jmDW4ist(DyFdFiWEcAv6tRZnX3UNWg0zRL88YGOG0B8NTnKPxhmZFZLjVsTXOuvrl9Wk)6EYLM95T27xUA2MkiQQCAulLjPallDKCEWHWuMdyA4cNI5PAKFrH8NrwDw6VBv2dS41AT4bHtzyF6e6qPhLUk9qDnUSEZlmUMpX6EDoZ7vpLu1gkl3inxBPSRpZJX6uEVxsQp(tPslq8NhwzHkAZtL)7IXVlcgZSRwtSJ(YNnolE5EIfsIOTesw6p7fUYpLSiE2fJhtlV7wswQNSs)pTKSi)ot4LiwNhSam0WYYvxZ0qLykYQKWlgFX4tjT)K)oI0fnNymYVE4SzVlk9xPDA)AaS4w6VcROD5eVKlg)IiOKNDXrxm(d(FjiLi7xCMLfyaJ)IV4Naz5HRY(*temporary) = nil
(*temporary) = "Plater"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Cell error:** 
Message: Interface/AddOns/PeaversUI/src/Profiles/Cell.lua:21: bad argument #1 to 'match' (string expected, got nil)
Time: Mon Sep 30 20:06:19 2024
Count: 1
Stack: Interface/AddOns/PeaversUI/src/Profiles/Cell.lua:21: bad argument #1 to 'match' (string expected, got nil)
[string "@Interface/AddOns/PeaversUI/src/Profiles/Cell.lua"]:21: in function `apply'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:102: in function `ApplyProfile'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:49: in function <Interface/AddOns/PeaversUI/src/Options/Profiles.lua:48>

Locals: settings = nil
Serializer = <table> {
}
LibDeflate = <table> {
 _MAJOR = "LibDeflate"
 _VERSION = "1.0.2-release"
 _COPYRIGHT = "LibDeflate 1.0.2-release Copyright (C) 2018-2021 Haoqian He. Licensed under the zlib License"
 internals = <table> {
 }
 _MINOR = 3
}

**Details error:**
Message: Interface/AddOns/PeaversUI/src/Profiles/Details.lua:9: attempt to call global 'IsAddOnLoaded' (a nil value)
Time: Mon Sep 30 20:12:19 2024
Count: 1
Stack: Interface/AddOns/PeaversUI/src/Profiles/Details.lua:9: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@Interface/AddOns/PeaversUI/src/Profiles/Details.lua"]:9: in function `apply'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:102: in function `ApplyProfile'
[string "@Interface/AddOns/PeaversUI/src/Options/Profiles.lua"]:49: in function <Interface/AddOns/PeaversUI/src/Options/Profiles.lua:48>

Locals: exportString = "T3x6YTnsAc(SS)yJPQiAPb3hBh7pOUSvBjkncYvnDeoeeijijgbcWga0YQ2O1J1(cSVy73rMjsacsrxJh3EMP6OlzsW84l)UYVlK5dMpC)drRRkNNLNIFSEz5ZXjvPfjXvL5PXztllEyYdrttw3SPknUknjhB3s8FpbA)6088Pj1n4xwLvpDwstc(5Knv0)MwKwT4f8tZswLSif(uZdrvWSmpzgm(fWOn28Hi4dJTEySXXw4Vx3at0Q0Qyy6NNTaNX5WKapyZAygsRry6VTjB6tXZsBsN2KXGzvADAtmautJNMmDzk(SIY4K80QgQpBQtJtkYwLG9ioz60uAzmlRozcSCx9sZYSPXZ2uSiLgrawsYZJxNN8sAvnIzIxuvUzTCSWfIA8QXHQkDDzvtmIGIZZkEQMHRvLFMXERINxvUkUawEmod69MvXWpxHZ00YvtsAIBYGFESPbaAPjnlJBklZBYwh)C2SMLpm221qntnLXpVS8HOFjjFtkIiRBskMMwhxNUyvArtDCE50NsNHZ2080eahwqRb(r4QaMXM8u8HfZGUvbWs86Kk4tiWVgw3tMuL(5mAvcZ(drpxwLptcSz1Xnvj1ljKcrFqsam8e5mAsz5tRsQEkUj9laXj73WvgqYBPduRJbubmmFgOiq)CCbk3gGfiBkGiRFbi(RG)z1KY8AK7QPezjMPntMU9rw1WA4jeOEoRyw5Z17LLRfVbiTnXtZrMla3wUoLyTueicfwK(80LWxtliw6iKEf38Y6uCiJqHaQHfBwdy)fLBAWHODkK8BtGHAz2IL5W)rnHWJix)ualwa)hj8vMxwfp5fHGzdiAWCAj508oBnc0G0bkNaTag5zy)Mxw0etDMxX4)3I(Rn9xh8VihonSYoEIOJ1ltaK2drJVz85YhX0UaGTTJGsS(KwbC2atuttwXIALoLMmGdJ0yalrqfr0v38RaRvjqZFi6(BUf(bGqNsegjtUbWK)YdJpYeLd(cqPaEPKPpnRQCDNprofileName = "PeaversUI"
(*temporary) = nil
(*temporary) = "Details"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

TipTac also doesn't have a profile to import in the addon settings.

**Comment by peavers** [comment]
This should now be resolve, for the meantime I've had to remove a lot of the import profiles until I've got the time to just fix it all, but for now Bartender/Cell/Details should be working along with weakaura and talent imports.
